### ISSUE TITLE
Include commit hooks for make lint.

### ISSUE THREAD

**Issue by sharkinsspatial** [pangeo-forge/pangeo-forge-aws-bakery#15]

**Comment by rabernat** [comment]
Seeing a lot of linting activity here. :+1:

Just wanted to point you at the pre-commit config for pangeo_forge: https://github.com/pangeo-forge/pangeo-forge/blob/master/.pre-commit-config.yaml

This has its own github workflow: https://github.com/pangeo-forge/pangeo-forge/blob/master/.github/workflows/pre-commit.yaml

Perhaps some of the same config can be used here?

**Comment by sharkinsspatial** [comment]
Thanks @rabernat. We hadn't looked at the pangeo forge pre-commit hooks when we set the repo up but I'll align things with that.
