### ISSUE TITLE
Further Perms for Dev Team

### ISSUE THREAD

**Issue by ciaransweet** [pangeo-forge/pangeo-forge-aws-bakery#17]
@rabernat is there any chance we can get less restrictive permissions on this repository?

I can't seem to set any kind of branch protection for when we get CI/CD in and I also can't set branches to delete upon PR merges

**Comment by rabernat** [comment]
I have just upgraded @pangeo-forge/dev-team to "admin" (from "maintain"). FYI @abarciauskas-bgse has had "admin" from the beginning.

**Comment by ciaransweet** [comment]
Awesome thanks @rabernat
