### ISSUE TITLE
Build worker images and register with ECR for new versions of pangeo-forge.

### ISSUE THREAD

**Issue by sharkinsspatial** [pangeo-forge/pangeo-forge-aws-bakery#21]
I'm not sure of the optimal approach here.  Can we use Github hooks to listen for release tags on `pangeo-forge/pangeo-forge` to build and register new images when new versions are released?

**Comment by ciaransweet** [comment]
@sharkinsspatial did some googling/asking around, I wish there was a GitHub Actions Slack... 😅 

From what I can tell, there's not a nice `listen` functionality that _doesn't_ require you to also fire off an event on the src repo. 

Luckily, we have access to both the src and dest repo. So we could try something like https://github.com/marketplace/actions/repository-dispatch to dispatch a `repository_dispatch` event from the `pangeo-forge/pangeo-forge` repo to the repos that depend on it. The biggest downside here is that `pangeo-forge/pangeo-forge` becomes knowledgeable of its dependants, which is pretty grim.

I'll keep googling though
