### ISSUE TITLE
Updating package versions in pangeo-notebook image.

### ISSUE THREAD

**Issue by sharkinsspatial** [pangeo-forge/pangeo-forge-aws-bakery#22]
As discussed we are updating the scheduler and workers to use `pangeo/pangeo-notebook:latest`.  But due to underlying package conflicts and the need to use the unreleased branches of packages that are not available in `conda-forge` (the current `master` branch of `xarray` and `pangeo-forge`).  I am currently using a somewhat hacky solution by executing `pip install` commands in the Conda `notebook` environment.  
```
FROM pangeo/pangeo-notebook:latest
RUN conda run -n notebook pip uninstall -y xarray
RUN conda run -n notebook pip install -I git+https://github.com/pydata/xarray@master
```
The biggest drawback here is that `pip` does not appear to respect the `--ignore-installed` or `--force-reinstall` flags when operating in a Conda environment and requires an explicit uninstall of the existing module.  My Conda experience is quite limited so perhaps there is a cleaner solution for this.  cc @rabernat

**Comment by TomAugspurger** [comment]
You might add the `--no-deps` flag to pip, assuming xarray's dev branch doesn't have any new dependencies it should be fine.
