### ISSUE TITLE
Update + contribute diagrams to github repo

### ISSUE THREAD

**Issue by abarciauskas-bgse** [pangeo-forge/pangeo-forge-aws-bakery#3]
Update diagram in https://paper.dropbox.com/doc/Pangeo-Forge-for-Dummies-PFFD--BGirFzXxuFidvJG74MhwoYVqAg-HE1fKXNS1mXSfQ05KcfLw based on comments and add to a github repo

**Comment by sharkinsspatial** [comment]
Closed by https://github.com/pangeo-forge/roadmap/pull/12
